### ISSUE TITLE
Inspecting SSL packets

### ISSUE THREAD

**Issue by xMadHat** [Mila432/Escape-from-Tarkov-Flea-Market-Bot#9]
Hello, I have recently started updating this script with current headers and endpoints. I have a few questions regarding the headers of various requests sent to certain endpoints. 

How did you figure out what JSON data the client sends to the endpoints that require it? The client doesn't start if you're proxying HTTPS requests so I can't inspect the packets there. Before I try to reverse the client to figure out what SSL library it uses and if I can dump the secrets I thought I'd ask you how you figured out what headers/JSONs to use for the requests. One or two endpoints have been moved around or changed completely and before I try running this script I need to figure out what they're used for. Once that is finished I theoretically should have a functioning script.

Naturally my fork is public and I plan on making a PR once it's finished. Even the smallest hint would be a huge help for me currently. Thank you for your time!

**Comment by Mila432** [comment]
I don't keep notes on old projects , so can't help you
